# Site settings
title: "James Yang Resume"
description: "An online resume of James Yang hosted by Github and Jekyll."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "James Yang"
resume_title:                   "Student at Carleton College"
resume_contact_email:           "yangj2@carleton.edu"
resume_contact_telephone:       "(952)495-7367"
resume_contact_address:         "300 North College St, Northfield, MN 55057"
resume_header_contact_info: "300 North College St, Northfield | (952)495-7367 | yangj2@carleton.edu"
resume_header_intro: "<p>This is the executive summary. You should write a few brief, concise, and meaningful sentences about yourself from a professional context, and your immediate career goals. Make the length appropriate for your needs, but K.I.S.S.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_projects:        true
resume_section_experience:      true
resume_section_skills:          true
resume_section_education:       true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/formidify"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/yang.jinhui.5"
  resume_linkedin_url:          "https://www.linkedin.com/in/james-yang-56182686/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_quora_url:             "https://www.quora.com/profile/James-Yang-106"
  # resume_website_url:           "http://joelglovier.com"
  # resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
